fix: windows theme issue
ckeditor/vite-plugin-ckeditor5 pull request #4
Opened 2023-01-07 07:38 UTC by PeterNelsonT

This is to fix https://github.com/ckeditor/vite-plugin-ckeditor5/issues/2
There seems to be inconsistency in path.join in unix and windows, which causes the plugin to fail fetching the theme css.
Updated https://github.com/ckeditor/vite-plugin-ckeditor5/blob/master/src/loaders/stylesLoader.ts to use normalizePath with path.join to make it consistent in unix and windows systems.

2023-01-07 17:07 UTC, PeterNelsonT commented
@pomek can review this?

2023-01-09 08:50 UTC, LukaszGudel requested changes
Thank you @PeterNelsonT for your contribution!

I've tested your changes and it works like a charm! I've added one small suggestion to imports, but other than that it works great.

2023-01-09 08:50 UTC, LukaszGudel commented on src/loaders/stylesLoader.ts
> +import { normalizePath } from 'vite';
```suggestion
import { normalizePath, type Plugin } from 'vite';
```

2023-01-09 09:03 UTC, LukaszGudel approved these changes

2023-01-09 09:24 UTC, pomek approved these changes
LGTM.

2023-01-09 10:01 UTC, merged